vich_uploader:
    db_driver: orm

    mappings:
        image_anounce:
            uri_prefix: /uploads/annonce
            upload_destination: '%kernel.project_dir%/public/uploads/annonce'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer